### ISSUE TITLE
Issues faced in main.dart while running

### ISSUE THREAD

**Issue by Adi0559** [Pranavchiku/Document-Wallet-App#1]
The method 'FlatButton' isn't defined for the type '_LandingPageState'.at  [106:13]
The method 'RaisedButton' isn't defined for the type '_LandingPageState'.at  [259:15]

**Comment by Pranavchiku** [comment]
These two are now deprecated in latest versions of flutter, you may find substitutes here: https://docs.flutter.dev/release/breaking-changes/buttons#context
